name: Build on Contentful Publish Event

on:
  repository_dispatch:
    types: [publish-event]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAPERCRANEFACTORY_OOO }}'
          channelId: live
          projectId: papercranefactory-ooo
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
